const BASE_URL = `${import.meta.env.VITE_APP_BASE_URL}/api`;

export const API_CONFIG = {
    AUTHENTICATION: {
        REQUEST_OTP: `${BASE_URL}/auth/request-login-otp`,
        VERIFY_OTP: `${BASE_URL}/auth/verify-login-otp`,
        GET_REFRESH_TOKEN: `${BASE_URL}/auth/refresh-token`,
        GET_MY_ACCOUNTS: `${BASE_URL}/user/private/my-accounts`,
        SWITCH_ACCOUNTS: `${BASE_URL}/auth/private/switch-account`,
    },
    USERS: {
        GET_ALL: `${BASE_URL}/users`,
        GET_BY_ID: `${BASE_URL}/users/:id`,
        CREATE: `${BASE_URL}/users/create`,
        UPDATE: `${BASE_URL}/users/update/:id`,
        DELETE: `${BASE_URL}/users/delete/:id`,
    },
    INTEREST_FORM: {
        GET_ALL: `${BASE_URL}/interest-form/private/getAll`,
        GET_BY_ID: `${BASE_URL}/interest-form/private/get`,
        CREATE: `${BASE_URL}/interest-form/save`,
        UPDATE: `${BASE_URL}/interest-form/private/update-status`,
        PROGRAM_STATUS_UPDATE: `${BASE_URL}/interest-form/private/update-form-program-status`,
        DELETE: `${BASE_URL}/interest-form/private`,
    },
    ACADEMIC_DETAILS: {
        GET_ALL: `${BASE_URL}/academic-year/getAll`,
        GET_BY_ID: `${BASE_URL}/academic-year`,
        CREATE: `${BASE_URL}/academic-year/private`,
        UPDATE: `${BASE_URL}/academic-year/private`,
        DELETE: `${BASE_URL}/academic-year/private`,
    },
    PROGRAMS: {
        GET_ALL: `${BASE_URL}/program/getAll`,
        GET_CURRENT_PROGRAM: `${BASE_URL}/program/current-year-program`,
        GET_REGISTERED_PROGRAM: `${BASE_URL}/program/private/my-programs`,
        GET_STUDENTS_REGISTERED_PROGRAM_WEEKS: `${BASE_URL}/program-academic-year/private/weeks/student`,
        GET_TEACHERS_REGISTERED_PROGRAM_WEEKS: `${BASE_URL}/program-academic-year/private/weeks/teacher`,
        PUBLISH_PROGRAM: `${BASE_URL}/program-academic-year/private`,
    },
    USER_MANAGEMENT: {
        CREATE: `${BASE_URL}/user/private/create`,
        UPDATE: `${BASE_URL}/user/private/update/:id`,
        GET_ALL: `${BASE_URL}/user/private/getAll`,
        GET_BY_ID: `${BASE_URL}/user/private/:id`,
        DELETE: `${BASE_URL}/users/delete/:id`,
    },
    STUDENTS_PROGRAM_MANAGEMENT: {
        ASSIGN_SINGLE_PROGRAM: `${BASE_URL}/student/private/academics-programs`,
        ASSIGN_MULTIPLE_PROGRAM: `${BASE_URL}/student/private/assign`,
        GET_ALL: `${BASE_URL}/student/private/search`,
        GET_BY_ID: `${BASE_URL}/student/private/getAll`,
        GET_USER_BY_ID: `${BASE_URL}/student/private`,
        UPDATE_USER_LEVEL: `${BASE_URL}/student/private/update-level`,
        GET_PROGRAM_WEEK_PROGRESS: `${BASE_URL}/student-program-progress/private/my-progress`,
    },
    TEACHERS_PROGRAM_MANAGEMENT: {
        ASSIGN_SINGLE_PROGRAM: `${BASE_URL}/teacher/private/academics-programs`,
        ASSIGN_MULTIPLE_PROGRAM: `${BASE_URL}/teacher/private/assign`,
        GET_ALL: `${BASE_URL}/teacher/private/search`,
        GET_BY_ID: `${BASE_URL}/teacher/private/getAll`,
        GET_USER_BY_ID: `${BASE_URL}/teacher/private`,
        UPDATE_USER_LEVEL: `${BASE_URL}/teacher/private/update-level`,
    },
    STUDENTS_PROGRAM_ACADEMC_YEAR: {
        GET_PROGRAM_ACADEMIC_YEAR: `${BASE_URL}/program-academic-year/private`,
        UPDATE_PROGRAM_ACADEMIC_YEAR: `${BASE_URL}/program-academic-year/private`,
    },
    STUDENTS_PROGRAM_CONTENTS_MANAGEMENT: {
        // programs weeks data
        GET_PROGRAM_WEEKS: `${BASE_URL}/program-weeks/private`,
        UPDATE_PROGRAM_WEEKS: `${BASE_URL}/program-weeks/private/week`,

        // program weeks contents
        // CREATE_PROGRAM_WEEKS_CONTENTS: `${BASE_URL}/program-weeks/private`,
        UPDATE_PROGRAM_WEEKS_CONTENTS: `${BASE_URL}/week-contents/private`,
        GET_PROGRAM_WEEKS_CONTENTS: `${BASE_URL}/program-weeks/private/week`,
        DELETE_PROGRAM_WEEKS_CONTENTS: `${BASE_URL}/program-weeks/private`,
    },
    STUDENTS_PROGRAM_ASSIGNMENTS: {
        GET_PROGRAM_ASSIGNMENTS: `${BASE_URL}/assignment/private`,
        UPDATE_PROGRAM_ASSIGNMENTS: `${BASE_URL}/assignment/private`,
        DELETE_PROGRAM_WEEKS_CONTENTS: `${BASE_URL}/assignment/private`,
        // PUT :- /api/assignment/private/{weekId}
        // DELETE :- /api/assignment/private/{id}
    },
    STUDENTS_PROGRAM_MANAGEMENT_ASSIGNMENTS: {
        SUBMIT_ASSIGNMENTS: `${BASE_URL}/student-assignment/private/assignment/submit`,
        GET_ASSIGNMENT_ANSWERS: (id) => `${BASE_URL}/student-assignment/private/assignment/${id}/answer`,
        GET_ASSIGNMENT_HISTORY: (id) => `${BASE_URL}/student-assignment/private/assignment/${id}/latest-submitted`,
        UPDATE_ASSIGNMENT_STATUS: `${BASE_URL}/student-week-progress/private`,
        UPDATE_COMPLETE_WEEK_STATUS: `${BASE_URL}/student-program-progress/private`,
    },
    UPLOAD_FILE: {
        SINGLE_FILE: `${BASE_URL}/upload/single`,
        MULTI_FILE: `${BASE_URL}/upload/multiple`,
    },
    DASHBOARD: {
        INTEREST_FORM_STATS: `${BASE_URL}/dashboard/private/interest-form-stats`,
        ADMIN_MAIN_DASHBOARD_STATS: `${BASE_URL}/dashboard/private/admin-main-dashboard-stats`,
        STUDENTS_PROGRAM_STATS: `${BASE_URL}/dashboard/private/program-students-stats`,
    },
    PROGRAM_DASHBOARD: {
        USERS_PROGRAM_STATS: `${BASE_URL}/dashboard/private/program/users-stats`,
        TOTAL_READING_MINUTES_BASED_ON_WEEKS: `${BASE_URL}/dashboard/private/program/reading-mins`,
        STUDENTS_PROGRESS_BASED_ON_WEEKS: `${BASE_URL}/dashboard/private/program/students-progress`,
        TOP_PERFORMERS: `${BASE_URL}/dashboard/private/program/top-performers`,
        STUDENT_COMPLETION_COUNT: `${BASE_URL}/dashboard/private/program/completion-count`,
        STUDENT_SUBMITTED_REVIEW_FORM: `${BASE_URL}/student-week-progress/private/students-assignments-forms`,
        STUDENT_SUBMITTED_REVIEW_FORM_METRICS_UPDATE: `${BASE_URL}/reading-form/private/reading-speed-metric`,
        STUDENT_SUBMITTED_REVIEW_FORM_MY_FORM: `${BASE_URL}/student-week-progress/private/my-assignment-form`,
        STUDENTS_PROGRAM_STATS: `${BASE_URL}/dashboard/private/program/my-stats`,
    },
    FEEDBACK_FORM: {
        SUBMIT_FEEDBACK: `${BASE_URL}/reading-form/private/submit`,
        REVIEW_FEEDBACK: `${BASE_URL}/review-feedback/private/update`,
    },
    ASSIGNING_STUDENTS_TO_TEACHERS: {
        GET_STUDENTS: `${BASE_URL}/teacher/private/assigned-students`,
        SEARCH_STUDENTS: `${BASE_URL}/teacher/private/search-students`,
        ASSIGN_STUDENTS: `${BASE_URL}/teacher/private/assign-students`,
        UNASSIGN_STUDENTS: `${BASE_URL}/teacher/private/unassign-students`,
    },
    FILES: {
        DOWNLOAD: `${BASE_URL}/excel/private/export/program-reading-report`,
        WEEKLY_REPORT: `${BASE_URL}/excel/private/export/students-assignments-forms`,
    },
    ASSESSMENTS: {
        CREATE_ASSESSMENTS: `${BASE_URL}/assessment/private/create`,
        GET_BY_WEEK_ID: `${BASE_URL}/assessment/private/week`,
        UPDATE_BY_ID: `${BASE_URL}/assessment/private/update`,
        DELETE_BY_ID: `${BASE_URL}/assessment/private/delete`,
        STUDENTS_MY_ASSESSMENTS_BY_ID: `${BASE_URL}/assessment/private/my-assessment/week`,
        SUBMIT_ASSESSMENTS: `${BASE_URL}/assessment/private/submit`,
    },
    RESEARCH_TOPICS: {
        UPLOAD_TOPICS: `${BASE_URL}/excel/private/import/topics`,
        SAVE_TOPICS: `${BASE_URL}/research/private/save-topics`,
        UPDATE_TOPICS_DUE_DATE: `${BASE_URL}/research/private/due-date`,
        UPDATE_TOPICS: `${BASE_URL}/research/private/update-topic`,
        DELETE_TOPICS: `${BASE_URL}/research/private/delete-topics`,
        GET_ALL_TOPICS: `${BASE_URL}/research/private/get-all-topics`,
        SELECT_TOPICS: `${BASE_URL}/research/private/student/select-topic`,
        SELECTED_TOPICS: `${BASE_URL}/research/private/selected-topics`,
        STUDENTS_SELECTED_TOPICS: `${BASE_URL}/research/private/student/selected-topics`,
        UPDATE_SELECTED_REQUEST: `${BASE_URL}/research/private/research-topic-selection`,
    },
    RESEARCH_PROGRAM: {
        GET_STUDENTS_WEEK: `${BASE_URL}/student-assignment-research/private/get-weeks`,
        SUBMIT_STUDENTS_ASSIGNMENTS: `${BASE_URL}/student-assignment-research/private/submit`,
        GET_ALL_STUDENTS_ASSIGNMENTS: `${BASE_URL}/student-assignment-research/private/students-research-assignments`,
        GET_STUDENTS_ASSIGNMENTS: `${BASE_URL}/student-assignment-research/private/my-research-assignment`,
        ADD_FEEDBACK: `${BASE_URL}/student-assignment-research/private/add-feedback`,
        UPDATE_ASSIGNMENT_STATUS: `${BASE_URL}/student-assignment-research/private/update-status`,
        UPDATE_RESEARCH_STATUS: `${BASE_URL}/student-assignment-research/private/staus`,
    },
    PROGRAM_PAYMENT: {
        SAVE: `${BASE_URL}/program-payment/private`,
        GET: `${BASE_URL}/program-payment/private`,
        UPDATE: `${BASE_URL}/program-payment/private`,
        DELETE: `${BASE_URL}/program-payment/private`,
    },
    REGISTRATION: {
        SEND_FORM: `${BASE_URL}/program-registration/private/create`,
        GET_REGISTERED_FORM_DATA : `${BASE_URL}/program-registration/get-reg-form`,
        SUBMIT_REGISTRATION_FORM : `${BASE_URL}/program-registration/submit`,
        UPDATE_REGISTRATION_FORM_STATUS : `${BASE_URL}/program-registration/private/status`,
    },
};
